### ISSUE TITLE
Poloniex not working

### ISSUE THREAD

**Issue by Pascal666** [zdavatz/rapflag#10]
I can't seem to get Poloniex to work.  Perhaps because I have no lending history?

```
Using config from /root/etc/config.yml
After 0 items. Loading upto 1000 lending_history items before 2017-10-11 17:01:55 -0500
Loaded 0 lending_history items
/usr/share/ruby/time.rb:325:in `_parse': no implicit conversion of nil into String (TypeError)
        from /usr/share/ruby/time.rb:325:in `parse'
        from /usr/local/share/gems/gems/rapflag-1.0.6/lib/rapflag/poloniex.rb:153:in `fetch_csv_history'
        from /usr/local/share/gems/gems/rapflag-1.0.6/bin/rapflag:29:in `block (2 levels) in <top (required)>'
        from /usr/local/share/gems/gems/rapflag-1.0.6/bin/rapflag:23:in `each'
        from /usr/local/share/gems/gems/rapflag-1.0.6/bin/rapflag:23:in `block in <top (required)>'
        from /usr/local/share/gems/gems/rapflag-1.0.6/bin/rapflag:21:in `each'
        from /usr/local/share/gems/gems/rapflag-1.0.6/bin/rapflag:21:in `<top (required)>'
        from /usr/local/bin/rapflag:23:in `load'
        from /usr/local/bin/rapflag:23:in `<main>'
```

**Comment by zdavatz** [comment]
Yes, that could be the problem. We build this to include lending histories.
